### PR TITLE
Resolved Bugs and added feature releated to Auction screen ,Order screen (Bids)

### PR DESCRIPTION
**Pull request by TejasDhole**
1.Added feature in Auction screen (Click anywhere to next screen)[[JIRA-228]](https://liveasy-logistics.atlassian.net/browse/LIVE-228?atlOrigin=eyJpIjoiYjc4OTdmMGEzMTMyNGY1MmJiMzFiNGFhOGM4Nzc0YmIiLCJwIjoiaiJ9)
2.Resolved Bug (Cancel button not working on web during signout)[[JIRA-231]](https://liveasy-logistics.atlassian.net/browse/LIVE-231?atlOrigin=eyJpIjoiNmIxODRjM2E5NmVlNDIwYmI5Yzc5NGEyZTg4MTJlMDAiLCJwIjoiaiJ9)
3.Updated UI  appearance of signout dialog box WEB (`Dialog box used to take all the screen and background was not visible)`
4.Updated the Bidding Api model variable` currentBid to transporterBid`
5.updated the pdfx plugin.`(pdfx ^2.6.0)`
6.fixed the bugs in auction bids screen`(when we click on bids and tranverse to other page and come back bids page remain open we have to show the bids screen again from the start) `

### CODE REVIEW

**Comment by Anik-Chakraborty** [comment]
image
getting this error while doing pub get or trying to run the project....
Error caused by pdfx package:
image
import it in usual way why importing it through github

**Comment by TejasDhole** [comment]
> image getting this error while doing pub get or trying to run the project.... Error caused by pdfx package: image why importing it through github rather than usual way...

Ive mention in pubspec.yaml file the reason behind importing from github ,it it because By importing in usual way its giving error image decoder call back error which they are still in process to solve this ,for time being this is the solution for the pdfx plugin

**Comment by TejasDhole** [comment]
> image getting this error while doing pub get or trying to run the project.... Error caused by pdfx package: image why importing it through github rather than usual way...

the pdfx import was done in last commit and its working in dev ,can you share your flutter doctor report ..!
ill get the look for that error and solve it soon

**Comment by TejasDhole** [comment]
> image getting this error while doing pub get or trying to run the project.... Error caused by pdfx package: image why importing it through github rather than usual way...

ive just updated the plugin version becuase yesterday they have updated the issue with this fix

**Review by liveasy97 — APPROVED** [review]

**Pull request merged**
